### ISSUE TITLE
Notas Gerais

### ISSUE THREAD

**Issue by davidrobert99** [jbarrinhos/Ficha2#1]
Não era bem necessario as funções printAreaTriangulo() e  printAreaRetangulo().

O  printCalcArea() era suposto receber os 3 argumentos por parametro em vez de ser usado double X = pedir..nextDouble(),.... dentro da função.

Tirando a função calcularFactorial(), o resto parecece-me bem.

**Comment by jbarrinhos** [comment]
As funções "printArea... ()" foram retiradas, realmente era uma dupla informação. E foi feito a correção tanto da função calArea() assim como a calcularFactorial()
